[package]
name = "drf-oxide-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"
description = "Rust core for drf-oxide: compiled Django REST framework serializers"
authors = ["Kamil Kobza <kamil1pl@gmail.com>"]
repository = "https://github.com/Kanzey/drf-oxide-core"
license = "MIT"

[lib]
name = "_drf_oxide_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.28", features = ["num-bigint"] }
jiter = { version = "0.13", features = ["python"] }
itoa = "1"

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
